# Generated by Django 2.2.4 on 2019-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='contatc_num',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.TextField(max_length=120),
        ),
    ]
